source "https://rubygems.org"

# Rails version
gem "rails", "~> 7.2.1", ">= 7.2.1.1"
# Database
gem "pg", "~> 1.1"
# Web server
gem "puma", ">= 5.0"
# CORS
gem 'rack-cors', require: 'rack/cors'
# Authentication and Authorization
gem 'doorkeeper'
gem 'devise'

# JSON serializer
gem 'jsonapi-serializer'

# Gems needed in all environments
gem "tzinfo-data", platforms: %i[windows jruby]
gem "bootsnap", require: false

# For Azure Key Vault management
gem 'azure_mgmt_key_vault'
gem 'azure_mgmt_authorization'

# Gems only for development and test environments
group :development, :test do
  # Debugging tools
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
  
  # Security analysis
  gem "brakeman", require: false
  
  # Code styling
  gem "rubocop-rails-omakase", require: false
end


