
services:
  # Backend Rails app
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f /rails/tmp/pids/server.pid && bin/rails server -b 0.0.0.0 -p 3000"
    # command: bash -c "rm -f /rails/tmp/pids/server.pid && bin/rails db:migrate && bin/rails server -b 0.0.0.0 -p 3000"

    environment:
      RAILS_ENV: development
      POSTGRES_USER: aclhub
      POSTGRES_PASSWORD: 23422
      POSTGRES_DB: api_development
      DATABASE_URL: postgresql://aclhub:23422@test-db:5432/api_development
    ports:
      - "3000:3000"
    depends_on:
      - test-db
    networks:
      - app-network
    volumes:
      - ./api:/rails
  
  # Frontend React app
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    networks:
      - app-network

  # PostgreSQL database
  # db:
  #   image: postgres
  #   environment:
  #     POSTGRES_USER: aclhub
  #     POSTGRES_PASSWORD: 23422
  #     POSTGRES_DB: api_development
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - db-data:/var/lib/postgresql/data
  #   networks:
  #     - app-network

  # PostgreSQL database for testing purposes
  test-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: aclhub
      POSTGRES_PASSWORD: 23422
      POSTGRES_DB: api_development
    ports:
      - "5433:5432"  # Use a different port to avoid conflict
    volumes:
      - test-db-data:/var/lib/postgresql/data  # Separate volume for test-db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
  test-db-data:
