# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: aclhub
  password: <%= ENV['ACLHUB_DB_PASS'] %>

development:
  <<: *default
  database: api_development
  host: db
  port: 5432

test:
  <<: *default
  database: api_test


production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
